//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace concert.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order:myclass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Booking = new HashSet<Booking>();
        }
    
        public int OrderID { get; set; }
        public Nullable<int> O_IDUSer { get; set; }
        public Nullable<int> O_SatatusID { get; set; }
        public Nullable<int> O_TotalPrice { get; set; }
        public string O_Date { get; set; }
        public byte[] O_IMG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Booking { get; set; }
        public virtual StatusOrder StatusOrder { get; set; }
    }
}
