//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace concert.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Show:myclass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Show()
        {
            this.Booking = new HashSet<Booking>();
        }
    
        public int IDShow { get; set; }
        public Nullable<int> IDBand { get; set; }
        public Nullable<int> IDPlace { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string MatTicket { get; set; }
        public string NameShow { get; set; }
        public byte[] Picture { get; set; }
    
        public virtual Band Band { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Booking { get; set; }
        public virtual Place Place { get; set; }
    }
}
